import 'package:flutter/material.dart';
import 'package:material_symbols_icons/symbols.dart';
import 'dart:io';
import 'dart:typed_data';
import 'package:flutter/foundation.dart' show kIsWeb;
import 'package:image_picker/image_picker.dart';
import '../../models/animal.dart';
import '../../services/animal_service.dart';
import '../../utils/constants.dart';
import '../../services/field_service.dart';
import '../../models/field_model.dart';
import '../../services/vaccine_service.dart';
import '../../models/vaccine_models.dart';
import 'package:intl/intl.dart';
import '../../widgets/animal_qr_dialog.dart'; // QR code après création

class AddAnimalScreen extends StatefulWidget {
  final Animal? animal;
  const AddAnimalScreen({super.key, this.animal});

  @override
  State<AddAnimalScreen> createState() => _AddAnimalScreenState();
}

class _AddAnimalScreenState extends State<AddAnimalScreen> {
  final _formKey = GlobalKey<FormState>();
  final AnimalService _animalService = AnimalService();
  final FieldService _fieldService = FieldService();
  final VaccineService _vaccineService = VaccineService();

  // Controllers
  final _nameController = TextEditingController();
  final _breedController = TextEditingController(); // used when "Other" is selected
  // _tagController removed — nodeId/tagNumber is auto-generated by the backend
  final _ageMonthsController = TextEditingController();

  // ── Breed selection state ──
  // _selectedBreed holds the dropdown value ('Other' triggers free-text input)
  String? _selectedBreed;
  static const String _breedOther = 'Other';

  /// Breeds per animal type — user can also pick "Other" for free text
  static const Map<String, List<String>> _breedsByType = {
    'cow': [
      'Holstein', 'Montbéliarde', 'Normande', 'Prim\'Holstein',
      'Charolaise', 'Limousine', 'Blonde d\'Aquitaine',
      'Angus', 'Hereford', 'Simmental',
      'Brune des Alpes', 'Tarentaise', 'Aubrac',
      'Frisonne', 'Jersey', 'Guernesey',
      'Tunisienne locale', 'Brune de l\'Atlas',
    ],
    'sheep': [
      'Mérinos', 'Suffolk', 'Dorper', 'Barbarine',
      'Queue fine de l\'Ouest', 'Sicilo-Sarde',
      'Lacaune', 'Brebis de Bergame', 'Mouton Ouled Djellal',
      'Texel', 'Ile-de-France', 'Mouton Charollais',
    ],
    'horse': [
      'Pur-sang arabe', 'Pur-sang anglais', 'Barbe',
      'Anglo-arabe', 'Selle français', 'Lusitanien',
      'Andalou', 'Frison', 'Lipizzan',
      'Quarter Horse', 'Appaloosa', 'Paint Horse',
      'Haflinger', 'Percheron', 'Boulonnais',
    ],
    'dog': [
      'Berger allemand', 'Berger belge Malinois', 'Berger de Beauce',
      'Labrador', 'Golden Retriever', 'Rottweiler',
      'Dobermann', 'Bouvier des Flandres', 'Chien de berger tunisien',
      'Sloughi', 'Aïdi (Chien de l\'Atlas)',
    ],
  };
  final _weightController = TextEditingController();
  final _notesController = TextEditingController();
  final _dailyMilkAvgController = TextEditingController();
  final _lactationNumberController = TextEditingController();
  final _birthWeightController = TextEditingController();
  final _birthCostController = TextEditingController();
  final _purchasePriceController = TextEditingController();
  final _salePriceController = TextEditingController();

  // State
  int _currentStep = 1;
  String _selectedType = 'cow';
  String _selectedSex = 'female';
  double _ageInMonths = 24;
  bool _isVaccinated = false;
  bool? _isPregnant; // null = unknown, true = yes, false = no
  bool _isLoading = false;
  
  // Field-based ownership
  List<FieldModel> _fields = [];
  String? _selectedFieldId;

  // Species-specific state
  String? _raceCategory;   // course, loisir, sport
  String? _trainingLevel;  // debutant, intermediaire, avance, confirme, elite
  String? _meatGrade;      // A, B, C
  String? _dogRole;        // garde, berger, compagnie

  // Financial & Genealogy State
  String _selectedOrigin = 'purchased'; // purchased | born
  String? _selectedMotherId;
  String? _selectedFatherId;
  List<Animal> _potentialParents = [];

  // Dynamic Vaccine Regulations
  List<VaccineRegulation> _regulations = [];
  bool _isLoadingRegulations = false;
  
  // Tracked data for each regulation/vaccine
  // Key: vaccine code, Value: {checked: bool, date: String, dose: double, isOther: bool, lot: String}
  final Map<String, Map<String, dynamic>> _vaccineSelections = {};

  bool get isEditMode => widget.animal != null;

  // ── Photo picker state ──
  File? _selectedImage;
  Uint8List? _webImageBytes; // web-only: bytes for Image.memory
  String? _existingImageUrl;
  final ImagePicker _picker = ImagePicker();

  @override
  void initState() {
    super.initState();
    if (isEditMode) {
      final a = widget.animal!;
      _nameController.text = a.name;
      _breedController.text = a.breed ?? '';
      // tagNumber is read-only — not editable by the user
      _weightController.text = a.weight?.toString() ?? '';
      _notesController.text = a.notes ?? '';
      _selectedType = a.animalType.toLowerCase();
      _selectedSex = a.sex.toLowerCase();
      _ageInMonths = a.age.toDouble();
      _isVaccinated = a.vaccination;
      _existingImageUrl = a.profileImage;

      // Restore breed selection: check if the saved breed is in the list
      if (a.breed != null && a.breed!.isNotEmpty) {
        final breeds = _breedsByType[a.animalType.toLowerCase()] ?? [];
        if (breeds.contains(a.breed)) {
          _selectedBreed = a.breed;
        } else {
          _selectedBreed = _breedOther;
          _breedController.text = a.breed!;
        }
      }

      // Financials
      _selectedOrigin = a.origin;
      _selectedMotherId = a.motherId;
      _selectedFatherId = a.fatherId;
      _birthWeightController.text = a.birthWeightKg?.toString() ?? '';
      _birthCostController.text = a.birthCost?.toString() ?? '';
      _purchasePriceController.text = a.purchasePrice?.toString() ?? '';
      _salePriceController.text = a.salePrice?.toString() ?? '';
      
      // Prefer vaccineRecords for modern sync
      if (a.vaccineRecords != null && a.vaccineRecords!.isNotEmpty) {
        // vaccineRecords are loaded into _vaccineSelections via _fetchRegulations()
      }
      
      _isPregnant = a.isPregnant;
      // Start at step 2 (Details) when editing
      _currentStep = 2;
    }
    _ageMonthsController.text = _ageInMonths.toInt().toString();
    _ageMonthsController.addListener(() {
      final val = double.tryParse(_ageMonthsController.text);
      if (val != null && val >= 1 && val <= 240) {
        setState(() => _ageInMonths = val);
      }
      // Values outside 1-240 are silently ignored — slider enforces the range visually
    });
    _fetchFields();
    _fetchPotentialParents();
  }

  Future<void> _fetchPotentialParents() async {
    try {
      final animals = await _animalService.getAnimals();
      if (mounted) setState(() {
        _potentialParents = animals;
      });
    } catch (_) {
      // Silently fail — parents list is optional
    }
  }

  Future<void> _fetchFields() async {
    try {
      final fields = await _fieldService.getFields();
      setState(() {
        _fields = fields;
        if (!isEditMode && _fields.isNotEmpty) {
          _selectedFieldId = _fields.first.id;
          _fetchRegulations(); // Start fetching for default field
        } else if (isEditMode) {
          _selectedFieldId = widget.animal?.fieldId;
          // Fetch regulations for the animal's field in edit mode
          if (_selectedFieldId != null) {
            _fetchRegulations();
          }
        }
      });
    } catch (_) {
      // Silently fail — fields list is optional
    }
  }

  Future<void> _fetchRegulations() async {
    if (_selectedFieldId == null) return;
    
    setState(() => _isLoadingRegulations = true);
    try {
      // Use the field-based endpoint which auto-resolves country from GPS
      final regs = await _vaccineService.getFieldRegulations(_selectedFieldId!, species: _selectedType);
      setState(() {
        _regulations = regs;
        for (var reg in _regulations) {
          final vCode = reg.vaccine?.code ?? reg.vaccineId;
          if (!_vaccineSelections.containsKey(vCode)) {
            _vaccineSelections[vCode] = {
              'checked': false,
              'date': DateFormat('yyyy-MM-dd').format(DateTime.now()),
              'dose': 1.0,
              'lot': '',
              'isOther': false,
              'name': reg.vaccine?.nameFr ?? reg.vaccine?.nameEn ?? reg.vaccineId,
            };
          }
        }

        // Fix #4 — pré-cocher les vaccins déjà administrés en mode édition
        if (isEditMode && widget.animal?.vaccineRecords != null) {
          for (final record in widget.animal!.vaccineRecords!) {
            final code = record.vaccine?.code ?? record.vaccineId;
            if (_vaccineSelections.containsKey(code)) {
              _vaccineSelections[code]!['checked'] = true;
              _vaccineSelections[code]!['date'] =
                  record.administeredAt.toIso8601String().split('T')[0];
              _vaccineSelections[code]!['dose'] = record.doseGiven;
            } else {
              // Vaccin existant non présent dans les réglementations → ajouter comme "OTHER"
              final otherId = 'OTHER_${record.id}';
              _vaccineSelections[otherId] = {
                'checked': true,
                'date': record.administeredAt.toIso8601String().split('T')[0],
                'dose': record.doseGiven,
                'lot': record.lotNumber ?? '',
                'isOther': true,
                'name': (record.vaccine?.code == 'OTHER' ? record.notes : record.vaccine?.nameFr)
                    ?? record.notes
                    ?? 'Vaccin',
              };
            }
          }
        }
      });
    } catch (_) {
      // Silently fail — regulations will be empty
    } finally {
      setState(() => _isLoadingRegulations = false);
    }
  }

  @override
  void dispose() {
    // All TextEditingControllers must be disposed to avoid memory leaks
    _nameController.dispose();
    _breedController.dispose();
    _ageMonthsController.dispose();
    _weightController.dispose();
    _notesController.dispose();
    _dailyMilkAvgController.dispose();
    _lactationNumberController.dispose();
    _birthWeightController.dispose();
    _birthCostController.dispose();
    _purchasePriceController.dispose();
    _salePriceController.dispose();
    super.dispose();
  }

  Future<void> _submit() async {
    if (!_formKey.currentState!.validate()) return;

    // Validate field selection
    if (_selectedFieldId == null) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(
          content: Text('Please select a field before saving.'),
          backgroundColor: Colors.orange,
        ),
      );
      return;
    }

    // Validate animal name
    if (_nameController.text.trim().isEmpty) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(
          content: Text('Animal name is required.'),
          backgroundColor: Colors.orange,
        ),
      );
      return;
    }

    // Validate breed "Other" — free text must not be empty
    if (_selectedBreed == _breedOther && _breedController.text.trim().isEmpty) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(
          content: Text('Please enter the breed name or select one from the list.'),
          backgroundColor: Colors.orange,
        ),
      );
      return;
    }

    setState(() => _isLoading = true);

    try {
      final animalData = {
        'name': _nameController.text,
        // Use free-text if "Other" selected, otherwise use the dropdown value
        'breed': (_selectedBreed == _breedOther || _selectedBreed == null)
            ? (_breedController.text.trim().isEmpty ? null : _breedController.text.trim())
            : _selectedBreed,
        'animalType': _selectedType,
        'age': _ageInMonths.toInt(),
        'ageYears': (_ageInMonths / 12).floor(),
        'sex': _selectedSex,
        'weight': double.tryParse(_weightController.text),
        // tagNumber is auto-generated by the backend — not sent by the user
        'notes': _notesController.text,
        'fieldId': _selectedFieldId,
        // Derive vaccination status from the checklist — true if any vaccine was checked
        'vaccination': _vaccineSelections.values.any((v) => v['checked'] == true) || _isVaccinated,
        // Fix #3 — ne pas envoyer vaccines dans le payload animal pour éviter
        // le double enregistrement (les vaccins sont créés séparément via VaccineService)
        // 'vaccines': null,
        
        // Financial & Genealogy
        'origin': _selectedOrigin,
        'motherId': _selectedMotherId,
        'fatherId': _selectedFatherId,
        'birthWeightKg': double.tryParse(_birthWeightController.text),
        'birthCost': double.tryParse(_birthCostController.text),
        'purchasePrice': double.tryParse(_purchasePriceController.text),
        // salePrice only relevant in edit mode (set via sell screen, not creation form)
        if (isEditMode) 'salePrice': double.tryParse(_salePriceController.text),

        // COW + female
        'isPregnant': (_selectedType == 'cow' && _selectedSex == 'female') ? _isPregnant : null,
        'lactationNumber': (_selectedType == 'cow' && _selectedSex == 'female')
            ? int.tryParse(_lactationNumberController.text)
            : null,
        'dailyMilkAvgL': (_selectedType == 'cow' && _selectedSex == 'female')
            ? double.tryParse(_dailyMilkAvgController.text)
            : null,
        // HORSE
        'raceCategory': _selectedType == 'horse' ? _raceCategory : null,
        'trainingLevel': _selectedType == 'horse' ? _trainingLevel : null,
        // SHEEP
        'meatGrade': _selectedType == 'sheep' ? _meatGrade : null,
        // DOG
        'dogRole': _selectedType == 'dog' ? _dogRole : null,
      };

      Animal animal;
      if (isEditMode) {
        animal = await _animalService.updateAnimal(widget.animal!.nodeId, animalData);
      } else {
        animal = await _animalService.createAnimal(animalData);
      }

      // ── Upload photo ──
      if (_selectedImage != null || _webImageBytes != null) {
        try {
          if (kIsWeb && _webImageBytes != null) {
            animal = await _animalService.uploadAnimalPhotoBytes(
                animal.nodeId, _webImageBytes!);
          } else if (_selectedImage != null) {
            animal = await _animalService.uploadAnimalPhoto(
                animal.nodeId, _selectedImage!);
          }
        } catch (e) {
          if (mounted) {
            ScaffoldMessenger.of(context).showSnackBar(
              SnackBar(
                content: Text('Warning: Photo upload failed - $e'),
                backgroundColor: Colors.orange,
                duration: const Duration(seconds: 4),
              ),
            );
          }
        }
      }

      // ── Record selected vaccinations ──
      final checkedSelections = _vaccineSelections.entries.where((e) => e.value['checked'] == true).toList();
      for (var entry in checkedSelections) {
        final sel = entry.value;
        try {
          await _vaccineService.createRecord(
            animalId: animal.id,
            vaccineCode: sel['isOther'] == true ? 'OTHER' : entry.key,
            administeredBy: 'Farmer',
            administeredAt: DateTime.parse(sel['date']),
            doseGiven: (sel['dose'] as num).toDouble(),
            notes: sel['isOther'] == true ? sel['name'] : null, // Store name in notes for OTHER
          );
        } catch (ve) {
          // Silently skip failed vaccine records
        }
      }

      // ── Generate Smart Planning ──
      // Fix #5 — ne générer le plan que si aucun vaccin n'a déjà été sélectionné
      // (évite les doublons si l'utilisateur a coché des vaccins à l'étape 3)
      if (!isEditMode && checkedSelections.isEmpty) {
        try {
          await _vaccineService.generateSmartPlan(animal.id);
        } catch (pe) {
          // Silently skip smart plan generation failure
        }
      }

      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text(isEditMode ? 'Animal mis à jour avec succès !' : 'Animal enregistré avec succès ! Plan généré.'),
            backgroundColor: AppColors.success,
          ),
        );

        // ── Afficher le QR code après création (pas en mode édition) ──
        // L'agriculteur peut imprimer ce QR et le coller sur l'animal
        if (!isEditMode) {
          await AnimalQrDialog.show(context, animal);
        }

        Navigator.pop(context, true);
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Error: ${e.toString()}')),
        );
      }
    } finally {
      if (mounted) setState(() => _isLoading = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: AppColors.wheatWarmClay,
      body: Container(
        color: AppColors.sageTint,
        child: Stack(
          children: [
            // Background Mesh Gradient
          Positioned(
            top: -100,
            left: -100,
            right: -100,
            height: 400,
            child: Opacity(
              opacity: 0.6,
              child: Stack(
                children: [
                  Positioned(
                    top: 0,
                    left: 0,
                    child: Container(
                      width: 400,
                      height: 400,
                      decoration: BoxDecoration(
                        shape: BoxShape.circle,
                        gradient: RadialGradient(
                          colors: [
                            AppColors.fieldFreshStart.withValues(alpha: 0.2),
                            AppColors.fieldFreshStart.withValues(alpha: 0.0),
                          ],
                        ),
                      ),
                    ),
                  ),
                  Positioned(
                    top: -50,
                    right: -50,
                    child: Container(
                      width: 350,
                      height: 350,
                      decoration: BoxDecoration(
                        shape: BoxShape.circle,
                        gradient: RadialGradient(
                          colors: [
                            AppColors.mistyBlue.withValues(alpha: 0.2),
                            AppColors.mistyBlue.withValues(alpha: 0.0),
                          ],
                        ),
                      ),
                    ),
                  ),
                ],
              ),
            ),
          ),

          SafeArea(
            child: Column(
              children: [
                _buildHeader(),
                Expanded(
                  child: SingleChildScrollView(
                    padding: const EdgeInsets.fromLTRB(24, 0, 24, 120),
                    child: Form(
                      key: _formKey,
                      child: _buildCurrentStep(),
                    ),
                  ),
                ),
              ],
            ),
          ),

          _buildBottomAction(),
        ],
      ),
    ),
    );
  }

  Widget _buildHeader() {
    return Padding(
      padding: const EdgeInsets.all(24.0),
      child: Column(
        children: [
          Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              Row(
                children: [
                  GestureDetector(
                    onTap: () => Navigator.pop(context),
                    child: _buildIconButton(Symbols.arrow_back_ios_new),
                  ),
                ],
              ),
              Text(
                isEditMode ? 'Edit Animal' : 'Add Animal',
                style: const TextStyle(
                  fontSize: 20,
                  fontWeight: FontWeight.w800,
                  color: Color(0xFF1F2937),
                ),
              ),
              _buildIconButton(Symbols.more_horiz),
            ],
          ),
          const SizedBox(height: 32),
          _buildStepper(),
        ],
      ),
    );
  }

  Widget _buildIconButton(IconData icon) {
    return Container(
      width: 40,
      height: 40,
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(12),
        border: Border.all(color: const Color(0xFFF1F5F9)),
        boxShadow: [
          BoxShadow(
            color: Colors.black.withValues(alpha: 0.05),
            blurRadius: 4,
            offset: const Offset(0, 2),
          ),
        ],
      ),
      child: Icon(icon, size: 20, color: const Color(0xFF4B5563)),
    );
  }

  Widget _buildStepper() {
    return Row(
      children: [
        _buildStepIndicator(1, 'Species', _currentStep >= 1),
        _buildStepIndicatorLine(_currentStep > 1),
        _buildStepIndicator(2, 'Details', _currentStep >= 2),
        _buildStepIndicatorLine(_currentStep > 2),
        _buildStepIndicator(3, 'Vaccines', _currentStep >= 3),
      ],
    );
  }

  Widget _buildStepIndicator(int step, String label, bool isActive) {
    return Column(
      children: [
        Container(
          width: 32,
          height: 32,
          decoration: BoxDecoration(
            shape: BoxShape.circle,
            color: isActive ? AppColors.mistyBlue : const Color(0xFFF1F5F9),
            boxShadow: isActive ? [
              BoxShadow(
                color: AppColors.mistyBlue.withValues(alpha: 0.3),
                blurRadius: 8,
                offset: const Offset(0, 4),
              )
            ] : null,
          ),
          child: Center(
            child: Text(
              '$step',
              style: TextStyle(
                color: isActive ? Colors.white : const Color(0xFF94A3B8),
                fontSize: 12,
                fontWeight: FontWeight.bold,
              ),
            ),
          ),
        ),
        const SizedBox(height: 8),
        Text(
          label.toUpperCase(),
          style: TextStyle(
            fontSize: 10,
            fontWeight: FontWeight.w800,
            color: isActive ? AppColors.mistyBlue : const Color(0xFF94A3B8),
            letterSpacing: 0.5,
          ),
        ),
      ],
    );
  }

  Widget _buildStepIndicatorLine(bool isActive) {
    return Expanded(
      child: Container(
        height: 3,
        margin: const EdgeInsets.only(bottom: 18, left: 4, right: 4),
        decoration: BoxDecoration(
          color: isActive ? AppColors.mistyBlue : const Color(0xFFE2E8F0),
          borderRadius: BorderRadius.circular(2),
        ),
      ),
    );
  }

  Widget _buildCurrentStep() {
    switch (_currentStep) {
      case 1:
        return _buildStep1();
      case 2:
        return _buildStep2();
      case 3:
        return _buildStep3();
      default:
        return _buildStep1();
    }
  }

  // ─── Photo picker ────────────────────────────────────────────────────────────

  Future<void> _pickImage(ImageSource source) async {
    final XFile? picked = await _picker.pickImage(
      source: source,
      maxWidth: 1200,
      maxHeight: 1200,
      imageQuality: 85,
    );
    if (picked != null) {
      if (kIsWeb) {
        final bytes = await picked.readAsBytes();
        setState(() {
          _webImageBytes = bytes;
          _selectedImage = null; // not used on web
        });
      } else {
        setState(() {
          _selectedImage = File(picked.path);
          _webImageBytes = null;
        });
      }
    }
  }

  void _showImageSourceSheet() {
    showModalBottomSheet(
      context: context,
      shape: const RoundedRectangleBorder(
        borderRadius: BorderRadius.vertical(top: Radius.circular(20)),
      ),
      builder: (_) => SafeArea(
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            const SizedBox(height: 8),
            Container(
              width: 40,
              height: 4,
              decoration: BoxDecoration(
                color: const Color(0xFFE2E8F0),
                borderRadius: BorderRadius.circular(2),
              ),
            ),
            const SizedBox(height: 16),
            ListTile(
              leading: const Icon(Icons.camera_alt),
              title: const Text('Take a photo'),
              onTap: () {
                Navigator.pop(context);
                _pickImage(ImageSource.camera);
              },
            ),
            ListTile(
              leading: const Icon(Icons.photo_library),
              title: const Text('Choose from gallery'),
              onTap: () {
                Navigator.pop(context);
                _pickImage(ImageSource.gallery);
              },
            ),
            if (_selectedImage != null || _existingImageUrl != null)
              ListTile(
                leading: const Icon(Icons.delete, color: Colors.red),
                title: const Text('Remove photo',
                    style: TextStyle(color: Colors.red)),
                onTap: () {
                  Navigator.pop(context);
                  setState(() {
                    _selectedImage = null;
                    _webImageBytes = null;
                    _existingImageUrl = null;
                  });
                },
              ),
            const SizedBox(height: 8),
          ],
        ),
      ),
    );
  }

  Widget _buildPhotoPickerSection() {
    final hasImage =
        _selectedImage != null || _webImageBytes != null || _existingImageUrl != null;
    return GestureDetector(
      onTap: _showImageSourceSheet,
      child: Container(
        height: 180,
        width: double.infinity,
        margin: const EdgeInsets.only(bottom: 32),
        decoration: BoxDecoration(
          color: Colors.white,
          borderRadius: BorderRadius.circular(20),
          border: Border.all(
            color: hasImage ? AppColors.mistyBlue : const Color(0xFFE2E8F0),
            width: hasImage ? 2 : 1,
          ),
          boxShadow: [
            BoxShadow(
              color: Colors.black.withValues(alpha: 0.04),
              blurRadius: 8,
              offset: const Offset(0, 2),
            ),
          ],
        ),
        child: ClipRRect(
          borderRadius: BorderRadius.circular(19),
          child: hasImage
              ? Stack(
                  fit: StackFit.expand,
                  children: [
                    _buildSelectedImageWidget(),
                    Positioned(
                      bottom: 10,
                      right: 10,
                      child: Container(
                        padding: const EdgeInsets.symmetric(
                            horizontal: 12, vertical: 6),
                        decoration: BoxDecoration(
                          color: Colors.black54,
                          borderRadius: BorderRadius.circular(20),
                        ),
                        child: const Row(
                          mainAxisSize: MainAxisSize.min,
                          children: [
                            Icon(Icons.edit, color: Colors.white, size: 14),
                            SizedBox(width: 4),
                            Text('Edit',
                                style: TextStyle(
                                    color: Colors.white, fontSize: 12)),
                          ],
                        ),
                      ),
                    ),
                  ],
                )
              : _buildPhotoPlaceholder(),
        ),
      ),
    );
  }

  /// Returns the correct image widget depending on platform and source.
  Widget _buildSelectedImageWidget() {
    // Web: newly picked image → use bytes
    if (kIsWeb && _webImageBytes != null) {
      return Image.memory(_webImageBytes!, fit: BoxFit.cover);
    }
    // Mobile: newly picked image → use File
    if (!kIsWeb && _selectedImage != null) {
      return Image.file(_selectedImage!, fit: BoxFit.cover);
    }
    // Existing image from server (both platforms)
    if (_existingImageUrl != null) {
      return Image.network(
        'http://${AppConfig.serverHost}:${AppConfig.serverPort}$_existingImageUrl',
        fit: BoxFit.cover,
        errorBuilder: (_, __, ___) => _buildPhotoPlaceholder(),
      );
    }
    return _buildPhotoPlaceholder();
  }

  Widget _buildPhotoPlaceholder() {
    return Column(
      mainAxisAlignment: MainAxisAlignment.center,
      children: [
        Container(
          padding: const EdgeInsets.all(16),
          decoration: const BoxDecoration(
            color: Color(0xFFF1F5F9),
            shape: BoxShape.circle,
          ),
          child: const Icon(Icons.add_a_photo_outlined,
              size: 32, color: Color(0xFF94A3B8)),
        ),
        const SizedBox(height: 12),
        const Text(
          'Add a photo',
          style: TextStyle(
              fontWeight: FontWeight.w700,
              fontSize: 15,
              color: Color(0xFF475569)),
        ),
        const SizedBox(height: 4),
        const Text(
          'Camera or gallery',
          style: TextStyle(fontSize: 12, color: Color(0xFF94A3B8)),
        ),
      ],
    );
  }

  // ─── Step 1: Species & Gender ───────────────────────────────────────────────
  Widget _buildStep1() {    final types = [
      {'id': 'cow',   'label': 'Cow',   'emoji': '🐄', 'icon': Symbols.cruelty_free},
      {'id': 'sheep', 'label': 'Sheep', 'emoji': '🐑', 'icon': Symbols.pest_control_rodent},
      {'id': 'horse', 'label': 'Horse', 'emoji': '🐎', 'icon': Symbols.emoji_nature},
      {'id': 'dog',   'label': 'Dog',   'emoji': '🐕', 'icon': Symbols.sound_detection_dog_barking},
    ];

    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        _buildPhotoPickerSection(),
        _buildLabel('Select Farm / Field'),
        const SizedBox(height: 12),
        Container(
          padding: const EdgeInsets.symmetric(horizontal: 16),
          decoration: BoxDecoration(
            color: Colors.white,
            borderRadius: BorderRadius.circular(20),
            border: Border.all(color: const Color(0xFFE2E8F0)),
          ),
          child: DropdownButtonHideUnderline(
            child: DropdownButton<String>(
              value: _selectedFieldId,
              isExpanded: true,
              hint: const Text('Select a field'),
              items: _fields.map((field) {
                return DropdownMenuItem<String>(
                  value: field.id,
                  child: Text(field.name),
                );
              }).toList(),
              onChanged: isEditMode ? null : (value) {
                setState(() => _selectedFieldId = value);
                _fetchRegulations();
              },
            ),
          ),
        ),
        const SizedBox(height: 32),
        const Row(
          mainAxisAlignment: MainAxisAlignment.spaceBetween,
          children: [
            Text(
              'Select Species',
              style: TextStyle(fontSize: 18, fontWeight: FontWeight.w800),
            ),
            Text(
              'Required',
              style: TextStyle(fontSize: 12, color: Color(0xFF94A3B8), fontWeight: FontWeight.w600),
            ),
          ],
        ),
        const SizedBox(height: 24),
        GridView.builder(
          shrinkWrap: true,
          physics: const NeverScrollableScrollPhysics(),
          gridDelegate: const SliverGridDelegateWithFixedCrossAxisCount(
            crossAxisCount: 2,
            mainAxisSpacing: 16,
            crossAxisSpacing: 16,
            childAspectRatio: 1.0,
          ),
          itemCount: types.length,
          itemBuilder: (context, index) {
            final type = types[index];
            final isSelected = _selectedType == type['id'];
            return GestureDetector(
              onTap: isEditMode ? null : () {
                setState(() {
                  _selectedType = type['id'] as String;
                  // Reset breed when animal type changes
                  _selectedBreed = null;
                  _breedController.clear();
                });
                _fetchRegulations();
              },
              child: AnimatedContainer(
                duration: const Duration(milliseconds: 200),
                decoration: BoxDecoration(
                  color: Colors.white,
                  borderRadius: BorderRadius.circular(24),
                  border: Border.all(
                    color: isSelected ? AppColors.mistyBlue : Colors.transparent,
                    width: 2,
                  ),
                  boxShadow: [
                    BoxShadow(
                      color: isSelected
                          ? AppColors.mistyBlue.withValues(alpha: 0.1)
                          : Colors.black.withValues(alpha: 0.03),
                      blurRadius: 10,
                      offset: const Offset(0, 4),
                    ),
                  ],
                ),
                child: Column(
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: [
                    Text(type['emoji'] as String, style: const TextStyle(fontSize: 36)),
                    const SizedBox(height: 12),
                    Text(
                      (type['label'] as String).toUpperCase(),
                      style: TextStyle(
                        fontSize: 11,
                        fontWeight: FontWeight.w800,
                        color: isSelected ? const Color(0xFF1F2937) : const Color(0xFF64748B),
                      ),
                    ),
                  ],
                ),
              ),
            );
          },
        ),
        const SizedBox(height: 32),
        _buildLabel('Gender'),
        Row(
          children: [
            _buildGenderOption('female', Symbols.female, 'Femelle'),
            const SizedBox(width: 16),
            _buildGenderOption('male', Symbols.male, 'Mâle'),
          ],
        ),
      ],
    );
  }

  Widget _buildGenderOption(String id, IconData icon, String label) {
    final isSelected = _selectedSex == id;
    return Expanded(
      child: GestureDetector(
        onTap: isEditMode ? null : () => setState(() => _selectedSex = id),
        child: Container(
          padding: const EdgeInsets.symmetric(vertical: 16),
          decoration: BoxDecoration(
            color: isSelected ? AppColors.mistyBlue.withValues(alpha: 0.1) : Colors.white,
            borderRadius: BorderRadius.circular(16),
            border: Border.all(
              color: isSelected ? AppColors.mistyBlue : const Color(0xFFF1F5F9),
              width: 2,
            ),
          ),
          child: Row(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              Icon(icon, size: 20, color: isSelected ? AppColors.mistyBlue : const Color(0xFF94A3B8)),
              const SizedBox(width: 8),
              Text(
                label,
                style: TextStyle(
                  fontSize: 13,
                  fontWeight: FontWeight.w800,
                  color: isSelected ? AppColors.mistyBlue : const Color(0xFF64748B),
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }

  // ─── Step 2: Profile Details ────────────────────────────────────────────────
  Widget _buildStep2() {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        const Text(
          'Profile Details',
          style: TextStyle(fontSize: 18, fontWeight: FontWeight.w800),
        ),
        const SizedBox(height: 24),

        // 1. Nom
        _buildLabel('Animal Name'),
        _buildTextField(_nameController, 'e.g. Bessie'),
        const SizedBox(height: 24),

        // 2. Race
        _buildLabel('Breed'),
        _buildBreedSelector(),
        const SizedBox(height: 32),

        // 3. Origine — EN PREMIER pour conditionner les champs suivants
        _buildLabel('Origin'),
        _buildOriginSection(),
        const SizedBox(height: 24),

        // 4. Généalogie (uniquement si né sur la ferme)
        if (_selectedOrigin == 'born') ...[
          _buildGenealogySection(),
          const SizedBox(height: 24),
        ],

        // 5. Données financières (prix d'achat OU coût de naissance selon l'origine)
        _buildFinancialSection(),
        const SizedBox(height: 32),

        // 6. Poids — saisi une seule fois ici
        //    (pour "born" : c'est le poids actuel, pas le poids de naissance qui est dans Financial)
        _buildLabel('Weight'),
        _buildTextField(
          _weightController,
          'e.g. 450',
          keyboardType: TextInputType.number,
          prefixIcon: Symbols.weight,
          suffix: 'KG',
        ),
        const SizedBox(height: 24),

        // 7. Âge — saisi une seule fois ici
        Row(
          mainAxisAlignment: MainAxisAlignment.spaceBetween,
          children: [
            _buildLabel('Age'),
            Container(
              padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 6),
              decoration: BoxDecoration(
                color: AppColors.mistyBlue.withValues(alpha: 0.1),
                borderRadius: BorderRadius.circular(10),
              ),
              child: Text(
                '${_ageInMonths.toInt()} Mois',
                style: const TextStyle(
                  color: AppColors.mistyBlue,
                  fontWeight: FontWeight.w800,
                  fontSize: 12,
                ),
              ),
            ),
          ],
        ),
        const SizedBox(height: 12),
        _buildAgeSlider(),
        const SizedBox(height: 12),
        _buildTextField(
          _ageMonthsController,
          'Âge exact en mois',
          keyboardType: TextInputType.number,
          suffix: 'MOIS',
        ),

        const SizedBox(height: 24),

        // 8. Tag / Node ID supprimé — généré automatiquement par le backend
        // Le QR code est affiché après la création de l'animal

        const SizedBox(height: 32),

        // --- Champs spécifiques à l'espèce ---
        if (_selectedType == 'cow' && _selectedSex == 'female') ...[
          _buildLabel('Reproduction'),
          _buildSectionCard(
            title: 'Gestation & Lactation',
            icon: Symbols.water_drop,
            iconColor: const Color(0xFF3B82F6),
            children: [
              _buildLabel('Gestante ?'),
              _buildPregnancyToggle(),
              const SizedBox(height: 20),
              _buildLabel('Numéro de lactation'),
              _buildTextField(
                _lactationNumberController,
                'Ex : 2',
                keyboardType: TextInputType.number,
                suffix: 'N°',
              ),
              const SizedBox(height: 20),
              _buildLabel('Production laitière moyenne'),
              _buildTextField(
                _dailyMilkAvgController,
                'Ex : 18.5',
                keyboardType: const TextInputType.numberWithOptions(decimal: true),
                suffix: 'L/J',
              ),
            ],
          ),
        ],
        if (_selectedType == 'horse') ...[
          _buildLabel('Profil Sportif'),
          _buildSectionCard(
            title: 'Compétition',
            icon: Symbols.sprint,
            iconColor: const Color(0xFFF59E0B),
            children: [
              _buildLabel('Catégorie de course'),
              _buildDropdown(
                value: _raceCategory,
                hint: 'Sélectionner...',
                items: const [
                  DropdownMenuItem(value: 'course',  child: Text('Course')),
                  DropdownMenuItem(value: 'loisir',  child: Text('Loisir')),
                  DropdownMenuItem(value: 'sport',   child: Text('Sport')),
                ],
                onChanged: (v) => setState(() => _raceCategory = v),
              ),
              const SizedBox(height: 20),
              _buildLabel('Niveau d\'entraînement'),
              _buildDropdown(
                value: _trainingLevel,
                hint: 'Sélectionner...',
                items: const [
                  DropdownMenuItem(value: 'debutant',      child: Text('Débutant')),
                  DropdownMenuItem(value: 'intermediaire', child: Text('Intermédiaire')),
                  DropdownMenuItem(value: 'avance',        child: Text('Avancé')),
                  DropdownMenuItem(value: 'confirme',      child: Text('Confirmé')),
                  DropdownMenuItem(value: 'elite',         child: Text('Élite')),
                ],
                onChanged: (v) => setState(() => _trainingLevel = v),
              ),
            ],
          ),
        ],
        if (_selectedType == 'sheep') ...[
          _buildLabel('Qualité Viande'),
          _buildSectionCard(
            title: 'Grade',
            icon: Symbols.star,
            iconColor: const Color(0xFF10B981),
            children: [
              _buildLabel('Grade Qualité'),
              _buildDropdown(
                value: _meatGrade,
                hint: 'Optionnel...',
                items: const [
                  DropdownMenuItem(value: 'A', child: Text('Grade A — Supérieur')),
                  DropdownMenuItem(value: 'B', child: Text('Grade B — Standard')),
                  DropdownMenuItem(value: 'C', child: Text('Grade C — Économique')),
                ],
                onChanged: (v) => setState(() => _meatGrade = v),
              ),
            ],
          ),
        ],
        if (_selectedType == 'dog') ...[
          _buildLabel('Rôle Professionnel'),
          _buildSectionCard(
            title: 'Spécialisation',
            icon: Symbols.shield,
            iconColor: const Color(0xFF8B5CF6),
            children: [
              _buildLabel('Sélectionner le Rôle'),
              _buildDogRolePicker(),
            ],
          ),
        ],
      ],
    );
  }

  Widget _buildAgeSlider() {
    return SliderTheme(
      data: SliderThemeData(
        activeTrackColor: AppColors.mistyBlue,
        inactiveTrackColor: const Color(0xFFF1F5F9),
        thumbColor: Colors.white,
        overlayColor: AppColors.mistyBlue.withValues(alpha: 0.2),
        trackHeight: 6,
        thumbShape: const RoundSliderThumbShape(enabledThumbRadius: 12, elevation: 3),
      ),
      child: Slider(
        min: 1,
        max: 240,
        value: _ageInMonths.clamp(1, 240),
        onChanged: (val) {
          setState(() {
            _ageInMonths = val;
            _ageMonthsController.text = val.toInt().toString();
          });
        },
      ),
    );
  }

  // ─── Step 3: Species-specific fields ────────────────────────────────────────
  Widget _buildStep3() {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        if (_isLoadingRegulations)
          const Center(child: Padding(
            padding: EdgeInsets.all(40.0),
            child: CircularProgressIndicator(),
          ))
        else if (_regulations.isEmpty)
          _buildSectionCard(
            title: 'No specific regulations found',
            icon: Symbols.info,
            iconColor: Colors.blue,
            children: [
              const Text('No mandatory vaccines detected for this region. Add them manually.'),
              const SizedBox(height: 16),
              _buildAddOtherButton(),
            ],
          )
        else ...[
          // --- Banner Section ---
          Container(
            padding: const EdgeInsets.all(20),
            decoration: BoxDecoration(
              color: const Color(0xFF2F7F34).withValues(alpha: 0.05),
              borderRadius: BorderRadius.circular(16),
              border: Border.all(color: const Color(0xFF2F7F34).withValues(alpha: 0.1)),
            ),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(
                  '${_regulations.length} vaccins chargés pour ${_selectedType.toUpperCase()} 🤖',
                  style: const TextStyle(fontSize: 18, fontWeight: FontWeight.bold, height: 1.2, color: Color(0xFF1F2937)),
                ),
                const SizedBox(height: 8),
                Builder(builder: (_) {
                  final field = _fields.where((f) => f.id == _selectedFieldId).firstOrNull;
                  final regionLabel = field?.regionCode ?? '';
                  return Text(
                    regionLabel.isNotEmpty 
                      ? 'Basé sur le protocole sanitaire de la région $regionLabel et les alertes en cours.'
                      : 'Basé sur le protocole sanitaire national et les alertes sanitaires en cours.',
                    style: const TextStyle(color: Color(0xFF64748B), fontSize: 13),
                  );
                }),
              ],
            ),
          ),
          const SizedBox(height: 24),

          // --- Checklist Section ---
          const Padding(
            padding: EdgeInsets.only(left: 4, bottom: 12),
            child: Text(
              'CHECKLIST SANITAIRE',
              style: TextStyle(fontSize: 12, fontWeight: FontWeight.bold, letterSpacing: 1.2, color: Color(0xFF64748B)),
            ),
          ),
          
          ..._regulations.map((reg) => _buildDynamicVaccineItem(reg)),
          
          const SizedBox(height: 16),
          Center(child: _buildAddOtherButton()),
        ],

        const SizedBox(height: 24),
        
        // Show selected "Other" vaccines
        ..._vaccineSelections.entries
            .where((e) => e.value['isOther'] == true)
            .map((e) => _buildOtherVaccineItem(e.key)),

        const SizedBox(height: 24),
        _buildLabel('Observations & Notes'),
        _buildTextField(
          _notesController, 
          'Observations particulières...', 
          maxLines: 4,
          prefixIcon: Symbols.notes,
        ),
      ],
    );
  }

  Widget _buildAddOtherButton() {
    return Container(
      width: double.infinity,
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(16),
        border: Border.all(color: const Color(0xFFE2E8F0)),
      ),
      child: TextButton.icon(
        onPressed: () {
          final id = 'OTHER_${DateTime.now().millisecondsSinceEpoch}';
          setState(() {
            _vaccineSelections[id] = {
              'checked': true,
              'date': DateFormat('yyyy-MM-dd').format(DateTime.now()),
              'dose': 1.0,
              'lot': '',
              'isOther': true,
              'name': '',
            };
          });
        },
        icon: const Icon(Symbols.add_circle, size: 20),
        label: const Text('Ajouter un autre vaccin'),
        style: TextButton.styleFrom(
          foregroundColor: const Color(0xFF2F7F34),
          padding: const EdgeInsets.symmetric(vertical: 16),
          textStyle: const TextStyle(fontWeight: FontWeight.bold),
        ),
      ),
    );
  }

  Widget _buildDynamicVaccineItem(VaccineRegulation reg) {
    final vCode = reg.vaccine?.code ?? reg.vaccineId;
    final sel = _vaccineSelections[vCode]!;
    final isChecked = sel['checked'] as bool;
    final isMandatory = reg.isMandatory;
    const greenColor = Color(0xFF2F7F34);

    return Container(
      margin: const EdgeInsets.only(bottom: 12),
      decoration: BoxDecoration(
        color: isChecked ? Colors.white : Colors.white.withValues(alpha: 0.7),
        borderRadius: BorderRadius.circular(16),
        border: Border.all(
          color: isChecked ? greenColor : const Color(0xFFF1F5F9),
          width: isChecked ? 2 : 1,
        ),
        boxShadow: [
          BoxShadow(
            color: Colors.black.withValues(alpha: 0.03),
            blurRadius: 4,
            offset: const Offset(0, 2),
          ),
        ],
      ),
      child: Column(
        children: [
          Container(
            padding: const EdgeInsets.all(16),
            decoration: BoxDecoration(
              color: isChecked ? greenColor.withValues(alpha: 0.05) : Colors.transparent,
              borderRadius: isChecked 
                ? const BorderRadius.vertical(top: Radius.circular(14)) 
                : BorderRadius.circular(14),
            ),
            child: Row(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Column(
                  children: [
                    SizedBox(
                      width: 24, height: 24,
                      child: Checkbox(
                        value: isChecked,
                        activeColor: greenColor,
                        side: BorderSide(color: greenColor.withValues(alpha: 0.3), width: 1.5),
                        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(4)),
                        onChanged: (val) => setState(() => sel['checked'] = val),
                      ),
                    ),
                    const SizedBox(height: 4),
                    Text(
                      isChecked ? 'FAIT' : 'PLANIFIER',
                      style: TextStyle(
                        fontSize: 10,
                        fontWeight: FontWeight.bold,
                        color: isChecked ? greenColor : const Color(0xFF94A3B8),
                      ),
                    ),
                  ],
                ),
                const SizedBox(width: 16),
                Expanded(
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Row(
                        children: [
                          Icon(Symbols.vaccines, color: isChecked || isMandatory ? greenColor : const Color(0xFF94A3B8), size: 20),
                          const SizedBox(width: 8),
                          Expanded(
                            child: Text(
                              reg.vaccine?.nameFr ?? reg.vaccineId,
                              style: const TextStyle(fontWeight: FontWeight.bold, fontSize: 15, color: Color(0xFF1E293B)),
                              overflow: TextOverflow.ellipsis,
                            ),
                          ),
                          if (isMandatory) ...[
                            const SizedBox(width: 6),
                            Container(
                              padding: const EdgeInsets.symmetric(horizontal: 6, vertical: 2),
                              decoration: BoxDecoration(
                                color: Colors.red.shade50,
                                borderRadius: BorderRadius.circular(4),
                              ),
                              child: Text('OBL.', style: TextStyle(color: Colors.red.shade700, fontSize: 9, fontWeight: FontWeight.bold)),
                            ),
                          ],
                        ],
                      ),
                      const SizedBox(height: 4),
                      Row(
                        children: [
                          Expanded(
                            child: Text(
                              isMandatory 
                                ? 'Majeur pour le contrôle sanitaire collectif.' 
                                : 'Optionnel mais fortement recommandé.',
                              style: const TextStyle(fontSize: 12, color: Color(0xFF64748B)),
                            ),
                          ),
                          if (reg.isRegional && reg.regionName != null)
                            Container(
                              margin: const EdgeInsets.only(left: 6),
                              padding: const EdgeInsets.symmetric(horizontal: 6, vertical: 2),
                              decoration: BoxDecoration(
                                color: Colors.blue.shade50,
                                borderRadius: BorderRadius.circular(4),
                              ),
                              child: Text(
                                reg.regionName!,
                                style: TextStyle(color: Colors.blue.shade700, fontSize: 10, fontWeight: FontWeight.w600),
                              ),
                            ),
                        ],
                      ),
                    ],
                  ),
                ),
              ],
            ),
          ),
          if (isChecked)
            Container(
              color: greenColor.withValues(alpha: 0.02),
              padding: const EdgeInsets.fromLTRB(56, 0, 16, 16),
              child: Container(
                padding: const EdgeInsets.all(12),
                decoration: BoxDecoration(
                  color: Colors.white,
                  borderRadius: BorderRadius.circular(12),
                  border: Border.all(color: greenColor.withValues(alpha: 0.2)),
                ),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    const Text(
                      "DATE D'ADMINISTRATION ET DOSE", 
                      style: TextStyle(fontSize: 10, fontWeight: FontWeight.bold, color: greenColor, letterSpacing: 0.5)
                    ),
                    const SizedBox(height: 12),
                    Row(
                      children: [
                        Expanded(child: _buildInlineDateField(sel)),
                        const SizedBox(width: 8),
                        Expanded(
                          child: _buildSmallNumberField(
                            'Dose (ml)',
                            initialValue: sel['dose'].toString(),
                            onChanged: (v) => sel['dose'] = double.tryParse(v) ?? 1.0,
                          ),
                        ),
                      ],
                    ),
                  ],
                ),
              ),
            ),
        ],
      ),
    );
  }

  Widget _buildSmallNumberField(String hint, {String? initialValue, Function(String)? onChanged}) {
    return Container(
      padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 2),
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(10),
        border: Border.all(color: const Color(0xFFE2E8F0)),
      ),
      child: TextFormField(
        initialValue: initialValue,
        onChanged: onChanged,
        keyboardType: TextInputType.number,
        style: const TextStyle(fontSize: 13, fontWeight: FontWeight.w600),
        decoration: InputDecoration(
          hintText: hint,
          hintStyle: const TextStyle(fontSize: 12, color: Color(0xFF94A3B8)),
          border: InputBorder.none,
          isDense: true,
          contentPadding: const EdgeInsets.symmetric(vertical: 10),
        ),
      ),
    );
  }

  Widget _buildOtherVaccineItem(String id) {
    final sel = _vaccineSelections[id]!;
    const greenColor = Color(0xFF2F7F34);

    return Container(
      margin: const EdgeInsets.only(bottom: 12),
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(16),
        border: Border.all(color: greenColor, width: 2),
        boxShadow: [
          BoxShadow(
            color: Colors.black.withValues(alpha: 0.03),
            blurRadius: 4,
            offset: const Offset(0, 2),
          ),
        ],
      ),
      child: Column(
        children: [
          Container(
            padding: const EdgeInsets.all(16),
            decoration: BoxDecoration(
              color: greenColor.withValues(alpha: 0.05),
              borderRadius: const BorderRadius.vertical(top: Radius.circular(14)),
            ),
            child: Row(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Column(
                  children: [
                    SizedBox(
                      width: 24, height: 24,
                      child: Checkbox(
                        value: true,
                        activeColor: greenColor,
                        side: BorderSide(color: greenColor.withValues(alpha: 0.3), width: 1.5),
                        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(4)),
                        onChanged: (_) {}, // Currently forced true for "other"
                      ),
                    ),
                    const SizedBox(height: 4),
                    const Text(
                      'FAIT',
                      style: TextStyle(
                        fontSize: 10,
                        fontWeight: FontWeight.bold,
                        color: greenColor,
                      ),
                    ),
                  ],
                ),
                const SizedBox(width: 16),
                Expanded(
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Row(
                        children: [
                          const Icon(Symbols.vaccines, color: greenColor, size: 20),
                          const SizedBox(width: 8),
                          Expanded(
                            child: TextFormField(
                              initialValue: sel['name'],
                              onChanged: (v) => sel['name'] = v,
                              style: const TextStyle(fontWeight: FontWeight.bold, fontSize: 15, color: Color(0xFF1E293B)),
                              decoration: const InputDecoration(
                                hintText: 'Nom du vaccin (ex: Grippe)',
                                hintStyle: TextStyle(color: Color(0xFF94A3B8), fontWeight: FontWeight.normal),
                                border: InputBorder.none,
                                isDense: true,
                                contentPadding: EdgeInsets.zero,
                              ),
                            ),
                          ),
                          IconButton(
                            icon: const Icon(Symbols.delete, color: Colors.red, size: 20),
                            onPressed: () => setState(() => _vaccineSelections.remove(id)),
                            padding: EdgeInsets.zero,
                            constraints: const BoxConstraints(),
                          ),
                        ],
                      ),
                      const SizedBox(height: 4),
                      const Text(
                        'Vaccin manuel ajouté au profil.',
                        style: TextStyle(fontSize: 12, color: Color(0xFF64748B)),
                      ),
                    ],
                  ),
                ),
              ],
            ),
          ),
          
          Container(
            color: greenColor.withValues(alpha: 0.02),
            padding: const EdgeInsets.fromLTRB(56, 0, 16, 16),
            child: Container(
              padding: const EdgeInsets.all(12),
              decoration: BoxDecoration(
                color: Colors.white,
                borderRadius: BorderRadius.circular(12),
                border: Border.all(color: greenColor.withValues(alpha: 0.2)),
              ),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  const Text(
                    "DATE D'ADMINISTRATION ET DOSE", 
                    style: TextStyle(fontSize: 10, fontWeight: FontWeight.bold, color: greenColor, letterSpacing: 0.5)
                  ),
                  const SizedBox(height: 12),
                  Row(
                    children: [
                      Expanded(child: _buildInlineDateField(sel)),
                      const SizedBox(width: 8),
                      Expanded(
                        child: _buildSmallNumberField(
                          'Dose (ml)',
                          initialValue: sel['dose'].toString(),
                          onChanged: (v) => sel['dose'] = double.tryParse(v) ?? 1.0,
                        ),
                      ),
                    ],
                  ),
                ],
              ),
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildInlineDateField(Map<String, dynamic> sel) {
    return GestureDetector(
      onTap: () async {
        final DateTime? picked = await showDatePicker(
          context: context,
          initialDate: DateTime.parse(sel['date']),
          firstDate: DateTime(2000),
          lastDate: DateTime.now(),
        );
        if (picked != null) {
          setState(() {
            sel['date'] = DateFormat('yyyy-MM-dd').format(picked);
          });
        }
      },
      child: Container(
        padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 8),
        decoration: BoxDecoration(
          color: Colors.white,
          borderRadius: BorderRadius.circular(10),
          border: Border.all(color: const Color(0xFFE2E8F0)),
        ),
        child: Row(
          children: [
            const Icon(Symbols.calendar_today, size: 16, color: Color(0xFF64748B)),
            const SizedBox(width: 8),
            Expanded(
              child: Text(
                sel['date'],
                style: const TextStyle(fontSize: 13, fontWeight: FontWeight.w600, color: Color(0xFF475569)),
                overflow: TextOverflow.ellipsis,
              ),
            ),
            const SizedBox(width: 4),
            const Text(
              'Modifier',
              style: TextStyle(fontSize: 10, fontWeight: FontWeight.bold, color: Color(0xFF2F7F34)),
            ),
          ],
        ),
      ),
    );
  }

  /// Card container reused in Step 3
  Widget _buildSectionCard({
    required String title,
    required IconData icon,
    required Color iconColor,
    required List<Widget> children,
  }) {
    return Container(
      padding: const EdgeInsets.all(20),
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(24),
        border: Border.all(color: const Color(0xFFF1F5F9)),
        boxShadow: [
          BoxShadow(
            color: Colors.black.withValues(alpha: 0.03),
            blurRadius: 10,
            offset: const Offset(0, 4),
          ),
        ],
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            children: [
              Container(
                width: 36,
                height: 36,
                decoration: BoxDecoration(
                  color: iconColor.withValues(alpha: 0.1),
                  borderRadius: BorderRadius.circular(10),
                ),
                child: Icon(icon, size: 20, color: iconColor),
              ),
              const SizedBox(width: 12),
              Text(
                title,
                style: const TextStyle(fontSize: 15, fontWeight: FontWeight.w800, color: Color(0xFF1F2937)),
              ),
            ],
          ),
          const SizedBox(height: 20),
          ...children,
        ],
      ),
    );
  }

  /// 3-state pregnancy toggle: Oui / Non / Inconnu
  Widget _buildPregnancyToggle() {
    final options = [
      {'value': true,  'label': 'Oui',      'color': const Color(0xFF10B981)},
      {'value': false, 'label': 'Non',      'color': const Color(0xFFEF4444)},
      {'value': null,  'label': 'Inconnu',  'color': const Color(0xFF94A3B8)},
    ];

    return Container(
      padding: const EdgeInsets.all(4),
      decoration: BoxDecoration(
        color: const Color(0xFFF1F5F9),
        borderRadius: BorderRadius.circular(16),
      ),
      child: Row(
        children: options.map((opt) {
          final isSelected = _isPregnant == opt['value'];
          final color = opt['color'] as Color;
          return Expanded(
            child: GestureDetector(
              onTap: () => setState(() => _isPregnant = opt['value'] as bool?),
              child: AnimatedContainer(
                duration: const Duration(milliseconds: 200),
                padding: const EdgeInsets.symmetric(vertical: 12),
                decoration: BoxDecoration(
                  color: isSelected ? color.withValues(alpha: 0.15) : Colors.transparent,
                  borderRadius: BorderRadius.circular(12),
                  border: Border.all(
                    color: isSelected ? color : Colors.transparent,
                    width: 1.5,
                  ),
                ),
                child: Center(
                  child: Text(
                    opt['label'] as String,
                    style: TextStyle(
                      fontSize: 13,
                      fontWeight: isSelected ? FontWeight.w800 : FontWeight.w600,
                      color: isSelected ? color : const Color(0xFF94A3B8),
                    ),
                  ),
                ),
              ),
            ),
          );
        }).toList(),
      ),
    );
  }

  /// Dog role picker: Garde / Berger / Compagnie
  Widget _buildDogRolePicker() {
    final roles = [
      {'id': 'garde',     'label': 'Garde',     'icon': Symbols.shield},
      {'id': 'berger',    'label': 'Berger',    'icon': Symbols.groups},
      {'id': 'compagnie', 'label': 'Compagnie', 'icon': Symbols.favorite},
    ];

    return Row(
      children: roles.map((role) {
        final isSelected = _dogRole == role['id'];
        return Expanded(
          child: GestureDetector(
            onTap: () => setState(() => _dogRole = role['id'] as String),
            child: Container(
              margin: const EdgeInsets.only(right: 8),
              padding: const EdgeInsets.symmetric(vertical: 14),
              decoration: BoxDecoration(
                color: isSelected ? AppColors.mistyBlue.withValues(alpha: 0.1) : const Color(0xFFF8FAFC),
                borderRadius: BorderRadius.circular(14),
                border: Border.all(
                  color: isSelected ? AppColors.mistyBlue : const Color(0xFFF1F5F9),
                  width: 1.5,
                ),
              ),
              child: Column(
                mainAxisAlignment: MainAxisAlignment.center,
                children: [
                  Icon(
                    role['icon'] as IconData,
                    size: 22,
                    color: isSelected ? AppColors.mistyBlue : const Color(0xFF94A3B8),
                  ),
                  const SizedBox(height: 6),
                  Text(
                    role['label'] as String,
                    style: TextStyle(
                      fontSize: 11,
                      fontWeight: FontWeight.w800,
                      color: isSelected ? AppColors.mistyBlue : const Color(0xFF64748B),
                    ),
                  ),
                ],
              ),
            ),
          ),
        );
      }).toList(),
    );
  }

  Widget _buildOriginSection() {
    return _buildSectionCard(
      title: 'Provenance',
      icon: Symbols.location_on,
      iconColor: Colors.teal,
      children: [
        Row(
          children: [
            _buildSelectableOption(
              label: 'Purchased',
              isSelected: _selectedOrigin == 'purchased',
              onTap: () => setState(() => _selectedOrigin = 'purchased'),
              icon: Symbols.shopping_cart,
            ),
            const SizedBox(width: 12),
            _buildSelectableOption(
              label: 'Born on Farm',
              isSelected: _selectedOrigin == 'born',
              onTap: () => setState(() {
                _selectedOrigin = 'born';
                _purchasePriceController.clear();
                // Refresh parents list when switching to born mode
                _fetchPotentialParents();
              }),
              icon: Symbols.child_care,
            ),
          ],
        ),
      ],
    );
  }

  Widget _buildGenealogySection() {
    return _buildSectionCard(
      title: 'Généalogie',
      icon: Symbols.family_history,
      iconColor: Colors.indigo,
      children: [
        _buildLabel('Mère (Mother)'),
        _buildAnimalPickerField(
          label: 'Mother',
          value: _selectedMotherId,
          hint: 'Select mother...',
          onSelected: (v) => setState(() => _selectedMotherId = v),
          genderFilter: 'female',
        ),
        const SizedBox(height: 24),
        _buildAnimalPickerField(
          label: 'Father',
          value: _selectedFatherId,
          hint: 'Select father...',
          onSelected: (v) => setState(() => _selectedFatherId = v),
          genderFilter: 'male',
        ),
      ],
    );
  }

  Widget _buildFinancialSection() {
    return _buildSectionCard(
      title: 'Données Financières',
      icon: Symbols.payments,
      iconColor: Colors.green,
      children: [
        if (_selectedOrigin == 'purchased') ...[
          _buildLabel('Prix d\'achat'),
          _buildTextField(
            _purchasePriceController,
            'Prix payé...',
            keyboardType: TextInputType.number,
            prefixIcon: Symbols.monetization_on,
            suffix: 'USD',
          ),
          const SizedBox(height: 16),
        ] else ...[
          _buildLabel('Coût de naissance'),
          _buildTextField(
            _birthCostController,
            'Frais véto/médocs...',
            keyboardType: TextInputType.number,
            prefixIcon: Symbols.medical_services,
          ),
          const SizedBox(height: 16),
          _buildLabel('Poids à la naissance'),
          _buildTextField(
            _birthWeightController,
            'Poids initial...',
            keyboardType: TextInputType.number,
            suffix: 'KG',
          ),
          const SizedBox(height: 16),
        ],
      ],
    );
  }


  Widget _buildSelectableOption({
    required String label,
    required bool isSelected,
    required VoidCallback onTap,
    required IconData icon,
  }) {
    return Expanded(
      child: GestureDetector(
        onTap: onTap,
        child: Container(
          padding: const EdgeInsets.symmetric(vertical: 16),
          decoration: BoxDecoration(
            color: isSelected ? AppColors.mistyBlue.withValues(alpha: 0.1) : Colors.white,
            borderRadius: BorderRadius.circular(16),
            border: Border.all(
              color: isSelected ? AppColors.mistyBlue : const Color(0xFFF1F5F9),
              width: 2,
            ),
          ),
          child: Column(
            children: [
              Icon(icon, size: 24, color: isSelected ? AppColors.mistyBlue : const Color(0xFF94A3B8)),
              const SizedBox(height: 8),
              Text(
                label,
                style: TextStyle(
                  fontSize: 13,
                  fontWeight: FontWeight.w800,
                  color: isSelected ? AppColors.mistyBlue : const Color(0xFF64748B),
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }

  Widget _buildAnimalPickerField({
    required String label,
    required String? value,
    required String hint,
    required void Function(String?) onSelected,
    required String genderFilter,
  }) {
    final selectedAnimal = _potentialParents.cast<Animal?>().firstWhere(
      (a) => a?.id == value,
      orElse: () => null,
    );

    return GestureDetector(
      onTap: () => _showAnimalPicker(
        title: 'Select $label',
        genderFilter: genderFilter,
        onSelected: onSelected,
      ),
      child: Container(
        padding: const EdgeInsets.symmetric(horizontal: 20, vertical: 16),
        decoration: BoxDecoration(
          color: Colors.white,
          borderRadius: BorderRadius.circular(20),
          border: Border.all(color: const Color(0xFFF1F5F9)),
          boxShadow: [
            BoxShadow(
              color: Colors.black.withValues(alpha: 0.02),
              blurRadius: 8,
              offset: const Offset(0, 4),
            ),
          ],
        ),
        child: Row(
          children: [
            Icon(
              genderFilter == 'female' ? Symbols.female : Symbols.male,
              color: const Color(0xFF94A3B8),
              size: 22,
            ),
            const SizedBox(width: 12),
            Expanded(
              child: Text(
                selectedAnimal != null ? '${selectedAnimal.name} (${selectedAnimal.tagNumber ?? selectedAnimal.nodeId})' : hint,
                style: TextStyle(
                  fontWeight: FontWeight.w600,
                  fontSize: 15,
                  color: selectedAnimal != null ? const Color(0xFF1F2937) : const Color(0xFFCBD5E1),
                ),
              ),
            ),
            const Icon(Symbols.search, color: Color(0xFF94A3B8), size: 20),
          ],
        ),
      ),
    );
  }

  void _showAnimalPicker({
    required String title,
    required String genderFilter,
    required void Function(String?) onSelected,
  }) {
    String searchQuery = '';
    
    showModalBottomSheet(
      context: context,
      isScrollControlled: true,
      backgroundColor: Colors.transparent,
      builder: (context) => StatefulBuilder(
        builder: (context, setModalState) {
          final filtered = _potentialParents.where((a) {
            final matchesType = a.animalType.toLowerCase() == _selectedType.toLowerCase();
            final matchesSex = a.sex.toLowerCase() == genderFilter.toLowerCase();
            final matchesSearch = a.name.toLowerCase().contains(searchQuery.toLowerCase()) ||
                                (a.tagNumber?.toLowerCase().contains(searchQuery.toLowerCase()) ?? false) ||
                                a.nodeId.toLowerCase().contains(searchQuery.toLowerCase());
            return matchesType && matchesSex && matchesSearch;
          }).toList();

          return Container(
            height: MediaQuery.of(context).size.height * 0.75,
            decoration: const BoxDecoration(
              color: Colors.white,
              borderRadius: BorderRadius.vertical(top: Radius.circular(32)),
            ),
            child: Column(
              children: [
                const SizedBox(height: 12),
                Container(width: 40, height: 4, decoration: BoxDecoration(color: const Color(0xFFF1F5F9), borderRadius: BorderRadius.circular(2))),
                Padding(
                  padding: const EdgeInsets.all(24),
                  child: Row(
                    children: [
                      Text(title, style: const TextStyle(fontSize: 20, fontWeight: FontWeight.w800)),
                      const Spacer(),
                      IconButton(onPressed: () => Navigator.pop(context), icon: const Icon(Symbols.close)),
                    ],
                  ),
                ),
                Padding(
                  padding: const EdgeInsets.symmetric(horizontal: 24),
                  child: Container(
                    padding: const EdgeInsets.symmetric(horizontal: 16),
                    decoration: BoxDecoration(color: const Color(0xFFF8FAFC), borderRadius: BorderRadius.circular(16)),
                    child: TextField(
                      onChanged: (v) => setModalState(() => searchQuery = v),
                      decoration: const InputDecoration(
                        hintText: 'Search by name or Tag ID...',
                        hintStyle: TextStyle(color: Color(0xFF94A3B8), fontSize: 14),
                        border: InputBorder.none,
                        icon: Icon(Symbols.search, color: Color(0xFF94A3B8), size: 20),
                      ),
                    ),
                  ),
                ),
                const SizedBox(height: 16),
                Expanded(
                  child: filtered.isEmpty
                      ? Center(
                          child: Column(
                            mainAxisAlignment: MainAxisAlignment.center,
                            children: [
                              Icon(Symbols.pets, size: 48, color: const Color(0xFFF1F5F9)),
                              const SizedBox(height: 16),
                              Text('No matching animals found', style: TextStyle(color: const Color(0xFF94A3B8), fontWeight: FontWeight.w600)),
                            ],
                          ),
                        )
                      : ListView.separated(
                          padding: const EdgeInsets.all(24),
                          itemCount: filtered.length,
                          separatorBuilder: (_, __) => const SizedBox(height: 12),
                          itemBuilder: (context, index) {
                            final animal = filtered[index];
                            return InkWell(
                              onTap: () {
                                onSelected(animal.id);
                                Navigator.pop(context);
                              },
                              borderRadius: BorderRadius.circular(16),
                              child: Container(
                                padding: const EdgeInsets.all(16),
                                decoration: BoxDecoration(
                                  border: Border.all(color: const Color(0xFFF1F5F9)),
                                  borderRadius: BorderRadius.circular(16),
                                ),
                                child: Row(
                                  children: [
                                    CircleAvatar(
                                      backgroundColor: AppColors.mistyBlue.withValues(alpha: 0.1),
                                      child: Text(animal.name[0], style: const TextStyle(color: AppColors.mistyBlue, fontWeight: FontWeight.bold)),
                                    ),
                                    const SizedBox(width: 16),
                                    Expanded(
                                      child: Column(
                                        crossAxisAlignment: CrossAxisAlignment.start,
                                        children: [
                                          Text(animal.name, style: const TextStyle(fontWeight: FontWeight.bold, fontSize: 16)),
                                          Text(animal.tagNumber ?? animal.nodeId, style: const TextStyle(color: Color(0xFF64748B), fontSize: 13)),
                                        ],
                                      ),
                                    ),
                                    const Icon(Symbols.chevron_right, color: Color(0xFFCBD5E1), size: 20),
                                  ],
                                ),
                              ),
                            );
                          },
                        ),
                ),
              ],
            ),
          );
        },
      ),
    );
  }

  /// Breed selector: dropdown with predefined breeds for the selected animal type
  /// + "Other" option that reveals a free-text field.
  Widget _buildBreedSelector() {
    final breeds = _breedsByType[_selectedType] ?? [];
    final items = [
      ...breeds.map((b) => DropdownMenuItem(value: b, child: Text(b))),
      const DropdownMenuItem(value: _breedOther, child: Text('Other (specify)')),
    ];

    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        // Dropdown
        _buildDropdown<String>(
          value: _selectedBreed,
          hint: 'Select a breed...',
          items: items,
          onChanged: (v) => setState(() {
            _selectedBreed = v;
            if (v != _breedOther) _breedController.clear();
          }),
        ),
        // Free-text field shown only when "Other" is selected
        if (_selectedBreed == _breedOther) ...[
          const SizedBox(height: 12),
          _buildTextField(
            _breedController,
            'Enter breed name...',
          ),
        ],
      ],
    );
  }

  /// Generic styled dropdown
  Widget _buildDropdown<T>({
    required T? value,
    required String hint,
    required List<DropdownMenuItem<T>> items,
    required void Function(T?) onChanged,
  }) {
    return Container(
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(20),
        border: Border.all(color: const Color(0xFFF1F5F9)),
        boxShadow: [
          BoxShadow(
            color: Colors.black.withValues(alpha: 0.02),
            blurRadius: 8,
            offset: const Offset(0, 4),
          ),
        ],
      ),
      child: DropdownButtonFormField<T>(
        initialValue: value,
        hint: Text(hint, style: const TextStyle(color: Color(0xFFCBD5E1), fontSize: 14)),
        items: items,
        onChanged: onChanged,
        decoration: const InputDecoration(
          contentPadding: EdgeInsets.symmetric(horizontal: 20, vertical: 16),
          border: InputBorder.none,
        ),
        style: const TextStyle(
          fontWeight: FontWeight.w600,
          fontSize: 15,
          color: Color(0xFF1F2937),
        ),
        icon: const Icon(Symbols.expand_more, color: Color(0xFF94A3B8)),
        dropdownColor: Colors.white,
        borderRadius: BorderRadius.circular(16),
      ),
    );
  }

  // --- Common Components ---
  Widget _buildLabel(String text) {
    return Padding(
      padding: const EdgeInsets.only(left: 4, bottom: 8),
      child: Text(
        text.toUpperCase(),
        style: const TextStyle(
          fontSize: 11,
          fontWeight: FontWeight.w800,
          color: Color(0xFF64748B),
          letterSpacing: 0.5,
        ),
      ),
    );
  }

  Widget _buildTextField(
    TextEditingController? controller,
    String hint, {
    TextInputType keyboardType = TextInputType.text,
    IconData? prefixIcon,
    String? suffix,
    int maxLines = 1,
    String? initialValue,
    bool readOnly = false,
    Function(String)? onChanged,
  }) {
    return Container(
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(20),
        border: Border.all(color: const Color(0xFFF1F5F9)),
        boxShadow: [
          BoxShadow(
            color: Colors.black.withValues(alpha: 0.02),
            blurRadius: 8,
            offset: const Offset(0, 4),
          ),
        ],
      ),
      child: TextFormField(
        controller: controller,
        initialValue: initialValue,
        onChanged: onChanged,
        keyboardType: keyboardType,
        maxLines: maxLines,
        readOnly: readOnly,
        style: const TextStyle(fontWeight: FontWeight.w600, fontSize: 16),
        decoration: InputDecoration(
          hintText: hint,
          hintStyle: const TextStyle(color: Color(0xFFCBD5E1), fontSize: 14),
          contentPadding: const EdgeInsets.all(20),
          border: InputBorder.none,
          prefixIcon: prefixIcon != null ? Icon(prefixIcon, color: const Color(0xFF94A3B8), size: 22) : null,
          suffixIcon: suffix != null ? Padding(
            padding: const EdgeInsets.only(right: 20),
            child: Column(
              mainAxisAlignment: MainAxisAlignment.center,
              children: [
                Text(suffix, style: const TextStyle(fontSize: 10, fontWeight: FontWeight.w800, color: Color(0xFF94A3B8))),
              ],
            ),
          ) : null,
        ),
      ),
    );
  }

  Widget _buildBottomAction() {
    final isLastStep = _currentStep == 3;

    return Positioned(
      bottom: 0,
      left: 0,
      right: 0,
      child: Container(
        height: 140,
        padding: const EdgeInsets.all(24),
        decoration: BoxDecoration(
          gradient: LinearGradient(
            begin: Alignment.bottomCenter,
            end: Alignment.topCenter,
            colors: [
              Colors.white,
              Colors.white.withValues(alpha: 0.9),
              Colors.white.withValues(alpha: 0),
            ],
          ),
        ),
        child: Column(
          mainAxisAlignment: MainAxisAlignment.end,
          children: [
            Row(
              children: [
                if (_currentStep > 1)
                  Padding(
                    padding: const EdgeInsets.only(right: 12),
                    child: _buildBackButton(),
                  ),
                Expanded(
                  child: GestureDetector(
                    onTap: _isLoading ? null : () {
                      if (isLastStep) {
                        _submit();
                      } else {
                        setState(() => _currentStep++);
                      }
                    },
                    child: AnimatedContainer(
                      duration: const Duration(milliseconds: 300),
                      height: 64,
                      decoration: BoxDecoration(
                        gradient: const LinearGradient(
                          colors: [AppColors.mistBlue, AppColors.mistyBlue],
                          begin: Alignment.topLeft,
                          end: Alignment.bottomRight,
                        ),
                        borderRadius: BorderRadius.circular(24),
                        boxShadow: [
                          BoxShadow(
                            color: AppColors.mistyBlue.withValues(alpha: 0.4),
                            blurRadius: 20,
                            offset: const Offset(0, 10),
                          ),
                        ],
                      ),
                      child: Center(
                        child: _isLoading
                          ? const SizedBox(width: 24, height: 24, child: CircularProgressIndicator(color: Colors.white, strokeWidth: 2.5))
                          : Row(
                            mainAxisAlignment: MainAxisAlignment.center,
                            children: [
                              Icon(isLastStep ? Symbols.check_circle : Symbols.arrow_forward_ios_rounded, color: Colors.white, size: 24),
                              const SizedBox(width: 12),
                              Text(
                                isLastStep
                                  ? (isEditMode ? 'Mettre à jour' : 'Enregistrer l\'animal')
                                  : 'Continuer', 
                                style: const TextStyle(
                                  color: Colors.white,
                                  fontSize: 18,
                                  fontWeight: FontWeight.bold,
                                ),
                              ),
                            ],
                          ),
                      ),
                    ),
                  ),
                ),
              ],
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildBackButton() {
    return GestureDetector(
      onTap: () => setState(() => _currentStep--),
      child: Container(
        width: 64,
        height: 64,
        decoration: BoxDecoration(
          color: Colors.white,
          borderRadius: BorderRadius.circular(24),
          border: Border.all(color: const Color(0xFFF1F5F9)),
        ),
        child: const Icon(Symbols.arrow_back_ios_new, color: Color(0xFF94A3B8), size: 20),
      ),
    );
  }
}